png(file="Plot 1.png", width = 480, height = 480)
dt <- read.csv('C:/Users/petrova/Desktop/temp/R/household_power_consumption.txt', header = TRUE, sep=';')
dtday <- subset(dt, dt$Date %in% c('1/2/2007','2/2/2007'))
hist(as.numeric(as.character(dtday$Global_active_power)), xlim = c(0,6), col='red', xlab = 'Global Active Power (kilowatts)', main = 'Global Active Power', axes = FALSE)
tx <- c(0,2,4,6)
ty <- seq(0,1200, 200)
axis(side = 1, at = tx)
axis(side = 2, at = ty)
dev.off()