setwd('C:/Users/petrova/Desktop/temp/R')
png(file="Plot 4.png", width = 480, height = 480)
dt <- read.csv('household_power_consumption.txt', header = TRUE, sep=';')
dtday <- subset(dt, dt$Date %in% c('1/2/2007','2/2/2007'))
Sys.setlocale("LC_ALL","English")
dtday$DateTime <- as.POSIXct(paste(as.Date(dtday$Date,format = "%d/%m/%Y"), dtday$Time))
par(mfcol=c(2,2))
plot((as.numeric(as.character(dtday$Global_active_power))) ~ dtday$DateTime, xlab = '', ylab = 'Global Active Power (kilowatts)', type='l')
plot((as.numeric(as.character(dtday$Sub_metering_1))) ~ dtday$DateTime, xlab = '', ylab = 'Energy Sub metering', type='l', col='black')
lines((as.numeric(as.character(dtday$Sub_metering_2))) ~ dtday$DateTime, xlab = '', ylab = 'Energy Sub metering', col='red')
lines((as.numeric(as.character(dtday$Sub_metering_3))) ~ dtday$DateTime, xlab = '', ylab = 'Energy Sub metering', col='blue')
legend(x = 'topright',legend = c('Sub_metering_1','Sub_metering_2','Sub_metering_3'), lwd = 1, col=c('black', 'red','blue'), bty = "n")
plot((as.numeric(as.character(dtday$Voltage))) ~ dtday$DateTime, xlab = 'datetime', ylab = 'Voltage', type='l', col='black')
plot((as.numeric(as.character(dtday$Global_reactive_power))) ~ dtday$DateTime, xlab = 'datetime', ylab = 'Global reactive power', type='l', col='black')
dev.off()